### PR TITLE
Added json array querystring translation option

### PR DESCRIPTION
**Pull request by fjarkaup**
Hello I'm new to Golang and Git, this is my first ever PR :)
I'm using https://goa.design/ to generate a micro service which I host in a Lambda in AWS. I'm using algnhsa to bridge from AWS API Gateway to the Goa generated microservice. The  "UseProxyPath" addition was a great addition but I got into trouble using array parameters in the querystring so I added this fix.

### CODE REVIEW

**Comment by akrylysov** [comment]
Hi! Thanks for your contribution! I'm not familiar with goagen. Is there a reason you need to support a custom JSON query string parameter format? Shouldn't goagen handle that for you?

**Comment by Amplus** [comment]
Hello @akrylysov 
I think the main reason for this is that apparently there is no standard way of handling parameters in the querysting so there is no correct way of doing it. See this post for example:
https://medium.com/raml-api/arrays-in-query-params-33189628fa68
and here is a discussion on the matter on stackoverflow:
https://stackoverflow.com/questions/31844045/how-to-pass-array-query-params-to-aws-api-gateway
I could of course switch from get to post to get around this issue but I rather want my search method to use get and have more friendly url. Since this isn't standardised I think other would benefit from this addition to algnhsa. This is basically what it does:

> 	// Converts array parameter in query string from json format html?param=[1,2,3]
	// to html?param=1&param=2&param=3 format

**Comment by akrylysov** [comment]
Thanks for explaining! AWS recently introduced support of multi-value parameters https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/. I'll update algnhsa as soon as https://github.com/aws/aws-lambda-go/pull/136 is merged.

**Comment by akrylysov** [comment]
https://github.com/akrylysov/algnhsa/pull/13

**Comment by Amplus** [comment]
@akrylysov thank you, #13 fixed this issue for me so the workaround I did in the Translate-get-array-parameter pull request is not needed anymore.

**Pull request closed without merging**
